spring:
  application:
    name: discovery-ha
  profiles:
    active: peer1
eureka:
  server:
    # 自我保护模式
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000

---
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
      defaultZone: http://localhost:8761/eureka
server:
  port: 8761
spring:
  profiles: peer1
#---
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
#server:
#  port: 8762
#spring:
#  profiles: peer2